# Database
spring.datasource.url=jdbc:mysql://localhost:3306/quick_bill_local
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.quickbill=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

# Local secrets import
spring.config.import=optional:classpath:application-dev-local.properties