spring:
  application:
    name: quick-bill-backend

  datasource:
    url: jdbc:mysql://localhost:3306/quick_bill_local
    username: root
    password: Eswar@0226
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # dev only
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.quickbill: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"
